api_branch : origin/master
api_parser : ~
api_cfgmod : clone
api_runner : ~
api_paths  : lib
env_make : ~
env_prep : get-composer
env_post : ci-coveralls,ci-codacy
php_conf : timezone
php_exts : igbinary
app_prep : dep-composer
app_post : ~
app_path : ~
pkg_name : arthur-doctrine-fixtures-bundle
pkg_desc : "providing advanced YAML-based data-fixture importing, including support for priority- or dependent-based import ordering, configurable per-table merge or purge import strategies, simple inter-fixture references, and more."
pkg_bndl : true
